/* Auto-generated from index.html — do not edit manually. */
#ifndef INDEX_HTML_H
#define INDEX_HTML_H

static const char index_html[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>LED Stripe Editor</title>\n"
    "<style>\n"
    "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    "body{font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif;background:#1a1a2e;color:#e0e0e0;min-height:100vh;padding:12px}\n"
    "#app{max-width:600px;margin:0 auto}\n"
    "h1{font-size:1.3rem;padding:12px 0;color:#fff;text-align:center;border-bottom:1px solid #333;margin-bottom:12px}\n"
    ".slot-list{display:flex;flex-direction:column;gap:8px}\n"
    ".slot-row{display:flex;align-items:center;background:#16213e;border-radius:8px;padding:12px;border:2px solid transparent;cursor:pointer;gap:10px;min-height:56px;transition:background .15s}\n"
    ".slot-row.active{border-color:#4ade80;background:#0d2210}\n"
    ".slot-radio{width:20px;height:20px;border-radius:50%;border:2px solid #555;flex-shrink:0}\n"
    ".slot-row.active .slot-radio{background:#4ade80;border-color:#4ade80}\n"
    ".slot-info{flex:1;overflow:hidden;min-width:0}\n"
    ".slot-num{font-size:.75rem;color:#888;margin-bottom:2px}\n"
    ".slot-text{font-size:.95rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n"
    ".slot-text.empty{color:#555;font-style:italic}\n"
    ".edit-btn{background:#2563eb;color:#fff;border:none;border-radius:6px;padding:0 14px;font-size:.9rem;cursor:pointer;flex-shrink:0;height:44px;min-width:44px}\n"
    ".edit-btn:active{background:#1d4ed8}\n"
    ".status-bar{margin-top:12px;padding:10px 12px;background:#16213e;border-radius:8px;display:flex;align-items:center;gap:8px;font-size:.85rem}\n"
    ".dot{width:10px;height:10px;border-radius:50%;flex-shrink:0;background:#f87171}\n"
    ".dot.on{background:#4ade80}\n"
    ".modal-bg{display:none;position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:100;overflow-y:auto;padding:16px}\n"
    ".modal-bg.open{display:block}\n"
    ".modal{background:#1e293b;border-radius:12px;padding:20px;max-width:480px;margin:0 auto}\n"
    ".modal-hdr{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}\n"
    ".modal-hdr h2{font-size:1.1rem;color:#fff}\n"
    ".xbtn{background:none;border:none;color:#888;font-size:1.4rem;cursor:pointer;padding:4px 8px;line-height:1}\n"
    ".xbtn:hover{color:#fff}\n"
    "#etxt{width:100%;min-height:72px;background:#0f172a;color:#e0e0e0;border:1px solid #334155;border-radius:6px;padding:10px;font-size:1rem;font-family:monospace;resize:vertical;max-height:160px}\n"
    "#etxt:focus{outline:none;border-color:#2563eb}\n"
    "#cprev{min-height:26px;margin:10px 0 4px;font-family:monospace;font-size:1.05rem;line-height:1.6;word-break:break-all;letter-spacing:.5px}\n"
    ".clabel{font-size:.8rem;color:#888;margin-bottom:8px}\n"
    ".cbtn-row{display:flex;flex-wrap:wrap;gap:10px;margin-bottom:16px}\n"
    ".cbtn{width:48px;height:48px;border-radius:10px;border:3px solid transparent;cursor:pointer;font-size:.7rem;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0}\n"
    ".cbtn:active,.cbtn:focus{border-color:#fff;outline:none}\n"
    ".mactions{display:flex;gap:10px;justify-content:flex-end}\n"
    ".sbtn{background:#16a34a;color:#fff;border:none;border-radius:8px;padding:0 24px;height:44px;font-size:1rem;cursor:pointer}\n"
    ".sbtn:active{background:#15803d}\n"
    ".cbtn2{background:#475569;color:#fff;border:none;border-radius:8px;padding:0 24px;height:44px;font-size:1rem;cursor:pointer}\n"
    ".cbtn2:active{background:#334155}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div id=\"app\">\n"
    "  <h1>LED Stripe Editor</h1>\n"
    "  <div class=\"slot-list\" id=\"slist\"></div>\n"
    "  <div class=\"status-bar\">\n"
    "    <div class=\"dot\" id=\"sdot\"></div>\n"
    "    <span id=\"stxt\">Disconnected</span>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"modal-bg\" id=\"mbg\">\n"
    "  <div class=\"modal\">\n"
    "    <div class=\"modal-hdr\">\n"
    "      <h2 id=\"mtitle\">Edit Slot</h2>\n"
    "      <button class=\"xbtn\" id=\"xbtn\">&#x2715;</button>\n"
    "    </div>\n"
    "    <textarea id=\"etxt\" placeholder=\"Enter text...\" maxlength=\"255\"></textarea>\n"
    "    <div id=\"cprev\"></div>\n"
    "    <div class=\"clabel\">Select text range, then tap a color:</div>\n"
    "    <div class=\"cbtn-row\" id=\"cbtns\"></div>\n"
    "    <div class=\"mactions\">\n"
    "      <button class=\"cbtn2\" id=\"cancelbtn\">Cancel</button>\n"
    "      <button class=\"sbtn\" id=\"savebtn\">Save</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<script>\n"
    "var COLS=[\n"
    "  {k:'r',n:'Red',bg:'#ef4444',fg:'#fff'},\n"
    "  {k:'g',n:'Green',bg:'#22c55e',fg:'#fff'},\n"
    "  {k:'b',n:'Blue',bg:'#3b82f6',fg:'#fff'},\n"
    "  {k:'c',n:'Cyan',bg:'#06b6d4',fg:'#000'},\n"
    "  {k:'y',n:'Yellow',bg:'#eab308',fg:'#000'},\n"
    "  {k:'m',n:'Magenta',bg:'#d946ef',fg:'#fff'},\n"
    "  {k:'w',n:'White',bg:'#f1f5f9',fg:'#000'}\n"
    "];\n"
    "var CMAP={};\n"
    "COLS.forEach(function(c){CMAP[c.k]=c.bg;});\n"
    "\n"
    "var PREVIEW_LEN=24;   /* max chars shown in slot list row */\n"
    "var MAX_RDELAY=30000; /* max reconnect backoff in ms */\n"
    "\n"
    "var ws,rtimer,rdelay=3000;\n"
    "var state={active:0,slots:[]};\n"
    "var eidx=-1,ecols=[];\n"
    "\n"
    "function connect(){\n"
    "  var proto=location.protocol==='https:'?'wss:':'ws:';\n"
    "  ws=new WebSocket(proto+'//'+location.host+'/ws');\n"
    "  ws.onopen=function(){rdelay=3000;setStatus(true);};\n"
    "  ws.onclose=function(){setStatus(false);sched();};\n"
    "  ws.onerror=function(){ws.close();};\n"
    "  ws.onmessage=function(e){\n"
    "    try{var m=JSON.parse(e.data);if(m.cmd==='state'){state={active:m.active,slots:m.slots};render();}}catch(x){}\n"
    "  };\n"
    "}\n"
    "function sched(){clearTimeout(rtimer);rtimer=setTimeout(function(){connect();rdelay=Math.min(rdelay*2,MAX_RDELAY);},rdelay);}\n"
    "function setStatus(ok){\n"
    "  document.getElementById('sdot').className='dot'+(ok?' on':'');\n"
    "  document.getElementById('stxt').textContent=ok?'Connected':'Disconnected';\n"
    "}\n"
    "function send(o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o));}\n"
    "function esc(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}\n"
    "\n"
    "function render(){\n"
    "  var el=document.getElementById('slist');\n"
    "  el.innerHTML='';\n"
    "  state.slots.forEach(function(s,i){\n"
    "    var row=document.createElement('div');\n"
    "    row.className='slot-row'+(i===state.active?' active':'');\n"
    "    var prev=s.text?(s.text.length>PREVIEW_LEN?s.text.slice(0,PREVIEW_LEN)+'\\u2026':s.text):'(empty)';\n"
    "    row.innerHTML='<div class=\"slot-radio\"></div>'+\n"
    "      '<div class=\"slot-info\"><div class=\"slot-num\">Slot '+(i+1)+'</div>'+\n"
    "      '<div class=\"slot-text'+(s.text?'':' empty')+'\">'+esc(prev)+'</div></div>'+\n"
    "      '<button class=\"edit-btn\" data-i=\"'+i+'\">&#x270f;&#xfe0f;</button>';\n"
    "    row.querySelector('.edit-btn').addEventListener('click',function(e){\n"
    "      e.stopPropagation();openModal(+this.getAttribute('data-i'));\n"
    "    });\n"
    "    row.addEventListener('click',function(){send({cmd:'activate',slot:i});});\n"
    "    el.appendChild(row);\n"
    "  });\n"
    "}\n"
    "\n"
    "function syncLen(n){\n"
    "  while(ecols.length<n)ecols.push('w');\n"
    "  if(ecols.length>n)ecols.length=n;\n"
    "}\n"
    "function renderPrev(){\n"
    "  var txt=document.getElementById('etxt').value;\n"
    "  var el=document.getElementById('cprev');\n"
    "  if(!txt){el.textContent='';return;}\n"
    "  syncLen(txt.length);\n"
    "  var h='';\n"
    "  for(var i=0;i<txt.length;i++){\n"
    "    var col=CMAP[ecols[i]]||'#f1f5f9';\n"
    "    var ch=txt[i]===' '?'&nbsp;':esc(txt[i]);\n"
    "    h+='<span style=\"color:'+col+'\">'+ch+'</span>';\n"
    "  }\n"
    "  el.innerHTML=h;\n"
    "}\n"
    "function openModal(i){\n"
    "  eidx=i;\n"
    "  var s=state.slots[i]||{text:'',colors:''};\n"
    "  document.getElementById('mtitle').textContent='Edit Slot '+(i+1);\n"
    "  document.getElementById('etxt').value=s.text;\n"
    "  ecols=s.colors.split('');\n"
    "  syncLen(s.text.length);\n"
    "  renderPrev();\n"
    "  buildCbtns();\n"
    "  document.getElementById('mbg').classList.add('open');\n"
    "  document.getElementById('etxt').focus();\n"
    "}\n"
    "function closeModal(){document.getElementById('mbg').classList.remove('open');eidx=-1;}\n"
    "function buildCbtns(){\n"
    "  var el=document.getElementById('cbtns');\n"
    "  el.innerHTML='';\n"
    "  COLS.forEach(function(c){\n"
    "    var b=document.createElement('button');\n"
    "    b.className='cbtn';\n"
    "    b.style.background=c.bg;\n"
    "    b.style.color=c.fg;\n"
    "    b.title=c.n;\n"
    "    b.textContent=c.n;\n"
    "    b.addEventListener('click',function(){applyCol(c.k);});\n"
    "    el.appendChild(b);\n"
    "  });\n"
    "}\n"
    "function applyCol(k){\n"
    "  var ta=document.getElementById('etxt');\n"
    "  var s=ta.selectionStart,e=ta.selectionEnd;\n"
    "  syncLen(ta.value.length);\n"
    "  var from=s===e?0:s,to=s===e?ecols.length:e;\n"
    "  for(var i=from;i<to;i++)ecols[i]=k;\n"
    "  renderPrev();\n"
    "}\n"
    "function saveSlot(){\n"
    "  if(eidx<0)return;\n"
    "  var txt=document.getElementById('etxt').value.slice(0,255);\n"
    "  syncLen(txt.length);\n"
    "  send({cmd:'save',slot:eidx,text:txt,colors:ecols.join('')});\n"
    "  closeModal();\n"
    "}\n"
    "\n"
    "document.getElementById('etxt').addEventListener('input',function(){syncLen(this.value.length);renderPrev();});\n"
    "document.getElementById('mbg').addEventListener('click',function(e){if(e.target===this)closeModal();});\n"
    "document.getElementById('xbtn').addEventListener('click',closeModal);\n"
    "document.getElementById('cancelbtn').addEventListener('click',closeModal);\n"
    "document.getElementById('savebtn').addEventListener('click',saveSlot);\n"
    "\n"
    "connect();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";

#endif /* INDEX_HTML_H */
